# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/microzed_axi_dma/microzed_axi_dma.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma || ORIG_REF_NAME==microzed_axi_dma} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_xlconcat_0_0/microzed_axi_dma_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_xlconcat_0_0 || ORIG_REF_NAME==microzed_axi_dma_xlconcat_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_dma_0_0/microzed_axi_dma_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_dma_0_0 || ORIG_REF_NAME==microzed_axi_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_ps7_0_axi_periph_0/microzed_axi_dma_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==microzed_axi_dma_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_axi_mem_intercon_0/microzed_axi_dma_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_axi_mem_intercon_0 || ORIG_REF_NAME==microzed_axi_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_xbar_0/microzed_axi_dma_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_xbar_0 || ORIG_REF_NAME==microzed_axi_dma_xbar_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/microzed_axi_dma_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_system_ila_0_0 || ORIG_REF_NAME==microzed_axi_dma_system_ila_0_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_1/microzed_axi_dma_processing_system7_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_processing_system7_0_1 || ORIG_REF_NAME==microzed_axi_dma_processing_system7_0_1} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_proc_sys_reset_0_1/microzed_axi_dma_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_proc_sys_reset_0_1 || ORIG_REF_NAME==microzed_axi_dma_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_auto_pc_1/microzed_axi_dma_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_auto_pc_1 || ORIG_REF_NAME==microzed_axi_dma_auto_pc_1} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_auto_us_1/microzed_axi_dma_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_auto_us_1 || ORIG_REF_NAME==microzed_axi_dma_auto_us_1} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_auto_us_0/microzed_axi_dma_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_auto_us_0 || ORIG_REF_NAME==microzed_axi_dma_auto_us_0} -quiet] -quiet

# IP: bd/microzed_axi_dma/ip/microzed_axi_dma_auto_pc_0/microzed_axi_dma_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microzed_axi_dma_auto_pc_0 || ORIG_REF_NAME==microzed_axi_dma_auto_pc_0} -quiet] -quiet

# XDC: bd/microzed_axi_dma/microzed_axi_dma_ooc.xdc
