# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_1/microzed_axi_dma_processing_system7_0_1.xci
# IP: The module: 'microzed_axi_dma_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_1/microzed_axi_dma_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microzed_axi_dma_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_1/microzed_axi_dma_processing_system7_0_1.xci
# IP: The module: 'microzed_axi_dma_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_processing_system7_0_1/microzed_axi_dma_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'microzed_axi_dma_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
