# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/microzed_axi_dma_system_ila_0_0.xci
# IP: The module: 'microzed_axi_dma_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/bd_a1fb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb || ORIG_REF_NAME==bd_a1fb} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/bd_a1fb_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_ila_lib_0 || ORIG_REF_NAME==bd_a1fb_ila_lib_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_1/bd_a1fb_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_g_inst_0 || ORIG_REF_NAME==bd_a1fb_g_inst_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_2/bd_a1fb_slot_0_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_0_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_3/bd_a1fb_slot_0_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_w_0 || ORIG_REF_NAME==bd_a1fb_slot_0_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_4/bd_a1fb_slot_0_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_b_0 || ORIG_REF_NAME==bd_a1fb_slot_0_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_5/bd_a1fb_slot_0_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_0_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_6/bd_a1fb_slot_0_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_r_0 || ORIG_REF_NAME==bd_a1fb_slot_0_r_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_7/bd_a1fb_slot_1_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_1_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_8/bd_a1fb_slot_1_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_w_0 || ORIG_REF_NAME==bd_a1fb_slot_1_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_9/bd_a1fb_slot_1_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_b_0 || ORIG_REF_NAME==bd_a1fb_slot_1_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_10/bd_a1fb_slot_1_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_1_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_11/bd_a1fb_slot_1_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_r_0 || ORIG_REF_NAME==bd_a1fb_slot_1_r_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_12/bd_a1fb_slot_2_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_2_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_13/bd_a1fb_slot_2_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_w_0 || ORIG_REF_NAME==bd_a1fb_slot_2_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_14/bd_a1fb_slot_2_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_b_0 || ORIG_REF_NAME==bd_a1fb_slot_2_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_15/bd_a1fb_slot_2_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_2_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_16/bd_a1fb_slot_2_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_r_0 || ORIG_REF_NAME==bd_a1fb_slot_2_r_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_17/bd_a1fb_slot_3_aw_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_3_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_18/bd_a1fb_slot_3_w_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_w_0 || ORIG_REF_NAME==bd_a1fb_slot_3_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_19/bd_a1fb_slot_3_b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_b_0 || ORIG_REF_NAME==bd_a1fb_slot_3_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_20/bd_a1fb_slot_3_ar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_3_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_21/bd_a1fb_slot_3_r_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_r_0 || ORIG_REF_NAME==bd_a1fb_slot_3_r_0} -quiet] -quiet

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1fb_ila_lib_0 || ORIG_REF_NAME==bd_a1fb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1fb_ila_lib_0 || ORIG_REF_NAME==bd_a1fb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/bd_a1fb_ila_lib_0_ooc.xdc

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/bd_a1fb_ooc.xdc

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/microzed_axi_dma_system_ila_0_0.xci
# IP: The module: 'microzed_axi_dma_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/bd_a1fb.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb || ORIG_REF_NAME==bd_a1fb} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/bd_a1fb_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_ila_lib_0 || ORIG_REF_NAME==bd_a1fb_ila_lib_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_1/bd_a1fb_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_g_inst_0 || ORIG_REF_NAME==bd_a1fb_g_inst_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_2/bd_a1fb_slot_0_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_0_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_3/bd_a1fb_slot_0_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_w_0 || ORIG_REF_NAME==bd_a1fb_slot_0_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_4/bd_a1fb_slot_0_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_b_0 || ORIG_REF_NAME==bd_a1fb_slot_0_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_5/bd_a1fb_slot_0_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_0_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_6/bd_a1fb_slot_0_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_0_r_0 || ORIG_REF_NAME==bd_a1fb_slot_0_r_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_7/bd_a1fb_slot_1_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_1_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_8/bd_a1fb_slot_1_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_w_0 || ORIG_REF_NAME==bd_a1fb_slot_1_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_9/bd_a1fb_slot_1_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_b_0 || ORIG_REF_NAME==bd_a1fb_slot_1_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_10/bd_a1fb_slot_1_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_1_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_11/bd_a1fb_slot_1_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_1_r_0 || ORIG_REF_NAME==bd_a1fb_slot_1_r_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_12/bd_a1fb_slot_2_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_2_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_13/bd_a1fb_slot_2_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_w_0 || ORIG_REF_NAME==bd_a1fb_slot_2_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_14/bd_a1fb_slot_2_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_b_0 || ORIG_REF_NAME==bd_a1fb_slot_2_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_15/bd_a1fb_slot_2_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_2_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_16/bd_a1fb_slot_2_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_2_r_0 || ORIG_REF_NAME==bd_a1fb_slot_2_r_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_17/bd_a1fb_slot_3_aw_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_aw_0 || ORIG_REF_NAME==bd_a1fb_slot_3_aw_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_18/bd_a1fb_slot_3_w_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_w_0 || ORIG_REF_NAME==bd_a1fb_slot_3_w_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_19/bd_a1fb_slot_3_b_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_b_0 || ORIG_REF_NAME==bd_a1fb_slot_3_b_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_20/bd_a1fb_slot_3_ar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_ar_0 || ORIG_REF_NAME==bd_a1fb_slot_3_ar_0} -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_21/bd_a1fb_slot_3_r_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_a1fb_slot_3_r_0 || ORIG_REF_NAME==bd_a1fb_slot_3_r_0} -quiet] -quiet

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1fb_ila_lib_0 || ORIG_REF_NAME==bd_a1fb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a1fb_ila_lib_0 || ORIG_REF_NAME==bd_a1fb_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/ip/ip_0/bd_a1fb_ila_lib_0_ooc.xdc

# XDC: /home/simon/FPGADEVELOPER/ALT/AXI-DMA-Lauri-Design/microzed_axi_dma/microzed_axi_dma.srcs/sources_1/bd/microzed_axi_dma/ip/microzed_axi_dma_system_ila_0_0/bd_0/bd_a1fb_ooc.xdc
