# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/simon/FPGADEVELOPER/HWD-CDMA-BRAM/HWD-CDMA-BRAM.srcs/sources_1/bd/design_1/ip/design_1_fir_memo_top_0_0/design_1_fir_memo_top_0_0.xci
# IP: The module: 'design_1_fir_memo_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/simon/FPGADEVELOPER/HWD-CDMA-BRAM/HWD-CDMA-BRAM.srcs/sources_1/bd/design_1/ip/design_1_fir_memo_top_0_0/src/Z7010 or Z7020 MicroZed with MBCC-IO-PCB-D_v2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_memo_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/simon/FPGADEVELOPER/HWD-CDMA-BRAM/HWD-CDMA-BRAM.srcs/sources_1/bd/design_1/ip/design_1_fir_memo_top_0_0/design_1_fir_memo_top_0_0.xci
# IP: The module: 'design_1_fir_memo_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/simon/FPGADEVELOPER/HWD-CDMA-BRAM/HWD-CDMA-BRAM.srcs/sources_1/bd/design_1/ip/design_1_fir_memo_top_0_0/src/Z7010 or Z7020 MicroZed with MBCC-IO-PCB-D_v2.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_memo_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
